// Automatically generated by MockGen. DO NOT EDIT!
// Source: ../development/scripts/../../kernel/syscall/syscall.go

package mock_syscall

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of SyscallFS interface
type MockSyscallFS struct {
	ctrl     *gomock.Controller
	recorder *_MockSyscallFSRecorder
}

// Recorder for MockSyscallFS (not exported)
type _MockSyscallFSRecorder struct {
	mock *MockSyscallFS
}

func NewMockSyscallFS(ctrl *gomock.Controller) *MockSyscallFS {
	mock := &MockSyscallFS{ctrl: ctrl}
	mock.recorder = &_MockSyscallFSRecorder{mock}
	return mock
}

func (_m *MockSyscallFS) EXPECT() *_MockSyscallFSRecorder {
	return _m.recorder
}

func (_m *MockSyscallFS) BindMountReadWrite(source string, mountPoint string) error {
	ret := _m.ctrl.Call(_m, "BindMountReadWrite", source, mountPoint)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockSyscallFSRecorder) BindMountReadWrite(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BindMountReadWrite", arg0, arg1)
}

func (_m *MockSyscallFS) BindMountReadOnly(source string, mountPoint string) error {
	ret := _m.ctrl.Call(_m, "BindMountReadOnly", source, mountPoint)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockSyscallFSRecorder) BindMountReadOnly(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BindMountReadOnly", arg0, arg1)
}

func (_m *MockSyscallFS) Unmount(mountPoint string) error {
	ret := _m.ctrl.Call(_m, "Unmount", mountPoint)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockSyscallFSRecorder) Unmount(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Unmount", arg0)
}
